### ISSUE TITLE
Is it possible to show camera half of screen

### ISSUE THREAD

**Issue by abhishek3999** [manateeworks/manateeworks-barcodescanner-ionic-starter#3]

**Comment by manateeworks** [comment]
Hi @abhishek3999 
Thank you for contacting Customer Service Department.

Scan in partial screen view
`mwbScanner.startScanning(x, y, width, height);`
or with a custom init and callback:
`mwbScanner.startScanning(function(result){
//custom callback
}, x, y, width, height);`

x, y, width, height     - rectangle of the view in percentages relative to the screen size
callback  - result callback

TODO: ADD HOW TO SET PARAMS WITH SETTINGS CALLS
 Scan fullscreen  -  mwbScanner.startScanning()
 Scan in view     -  mwbScanner.startScanning(0,4,100,50)
 Pause/Resume     -  mwbScanner.togglePauseResume()
 Close            -  mwbScanner.closeScanner()
 Flash            -  mwbScanner.toggleFlash()
 Zoom             -  mwbScanner.toggleZoom()

Regards,

**Comment by abhishek3999** [comment]
Hi,

Thanks for response.
Could you please provide tutorial with ionic 4 framework.
Provided example is not working.
Giving error as index.html file is not loading.

Thanks

**Comment by manateeworks** [comment]
Hi 
Please use our new Ionic - https://cmbdn.cognex.com/ionic_demo_app_using_cmbsdk
Knowledge Base - https://cmbdn.cognex.com/v2.1.x/knowledge/cordova-plugin-for-cmbsdk/installation
Download Page - https://cmbdn.cognex.com/download

Regards,
